apiVersion: apps/v1
kind: Deployment
meta
  name: phishguard-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phishguard
  template:
    spec:
      containers:
      - name: phishguard
        image: phishguard:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "backend.settings"
